update 'quest_locale_ru' SET Title = 'Квест на болотную тварину', Description = 'Описание квеста' where QuestId = '1'; 
update 'quest' SET StartDialogId = '2', EndDialogId = '15', StartQuestEventType = '1', EndQuestEventType = '1' where Id = '1'; 
insert into 'quest_objectives' (QuestId) values ('1') ; 
insert into 'quest_objectives_locale_ru' (ObjectiveId) values ('1'); 
insert into 'quest_objectives' (QuestId) values ('1') ; 
insert into 'quest_objectives_locale_ru' (ObjectiveId) values ('2'); 
insert into 'quest_objectives' (QuestId) values ('1') ; 
insert into 'quest_objectives_locale_ru' (ObjectiveId) values ('3'); 
insert into 'quest_objectives' (QuestId) values ('1') ; 
insert into 'quest_objectives_locale_ru' (ObjectiveId) values ('4'); 
insert into 'quest_objectives' (QuestId) values ('1') ; 
insert into 'quest_objectives_locale_ru' (ObjectiveId) values ('5'); 
insert into 'quest_objectives' (QuestId) values ('1') ; 
insert into 'quest_objectives_locale_ru' (ObjectiveId) values ('6'); 
update 'quest_locale_ru' SET Title = 'Квест на болотную тварину', Description = 'Описание квеста' where QuestId = '1'; 
update 'quest' SET StartDialogId = '2', EndDialogId = '15', StartQuestEventType = '1', EndQuestEventType = '1' where Id = '1'; 
update 'quest_objectives' SET Type='8', TargetId='6', Amount='1',isOptional ='0' where QuestId='1' and Id ='1'; 
update 'quest_objectives_locale_ru' SET Title='Задача' where ObjectiveId = '1'; 
update 'quest_objectives' SET Type='8', TargetId='11', Amount='1',isOptional ='0' where QuestId='1' and Id ='2'; 
update 'quest_objectives_locale_ru' SET Title='Задача' where ObjectiveId = '2'; 
update 'quest_objectives' SET Type='8', TargetId='16', Amount='1',isOptional ='0' where QuestId='1' and Id ='3'; 
update 'quest_objectives_locale_ru' SET Title='Задача' where ObjectiveId = '3'; 
update 'quest_objectives' SET Type='8', TargetId='17', Amount='1',isOptional ='0' where QuestId='1' and Id ='4'; 
update 'quest_objectives_locale_ru' SET Title='Задача' where ObjectiveId = '4'; 
update 'quest_objectives' SET Type='8', TargetId='1', Amount='1',isOptional ='0' where QuestId='1' and Id ='5'; 
update 'quest_objectives_locale_ru' SET Title='Задача' where ObjectiveId = '5'; 
update 'quest_objectives' SET Type='8', TargetId='1', Amount='1',isOptional ='0' where QuestId='1' and Id ='6'; 
update 'quest_objectives_locale_ru' SET Title='Задача' where ObjectiveId = '6'; 
delete from 'quest_objectives' where Id =5; 
delete from 'quest_objectives_locale_ru' where ObjectiveId =5; 
delete from 'quest_objectives' where Id =6; 
delete from 'quest_objectives_locale_ru' where ObjectiveId =6; 
update 'quest_locale_ru' SET Title = 'Квест на болотную тварину', Description = 'Описание квеста' where QuestId = '1'; 
update 'quest' SET StartDialogId = '2', EndDialogId = '15', StartQuestEventType = '1', EndQuestEventType = '1' where Id = '1'; 
update 'quest_objectives' SET Type='8', TargetId='6', Amount='1',isOptional ='0' where QuestId='1' and Id ='1'; 
update 'quest_objectives_locale_ru' SET Title='Задача' where ObjectiveId = '1'; 
update 'quest_objectives' SET Type='8', TargetId='16', Amount='1',isOptional ='0' where QuestId='1' and Id ='2'; 
update 'quest_objectives_locale_ru' SET Title='Задача' where ObjectiveId = '2'; 
update 'quest_objectives' SET Type='8', TargetId='17', Amount='1',isOptional ='0' where QuestId='1' and Id ='3'; 
update 'quest_objectives_locale_ru' SET Title='Задача' where ObjectiveId = '3'; 
update 'quest_objectives' SET Type='8', TargetId='11', Amount='1',isOptional ='0' where QuestId='1' and Id ='4'; 
update 'quest_objectives_locale_ru' SET Title='Задача' where ObjectiveId = '4'; 
