delete from 'quest' where Id =5; 
delete from 'quest_locale_ru' where QuestId =5; 
delete from 'quest_objectives_locale_ru' where ObjectiveId =6; 
delete from 'quest_objectives_locale_ru' where ObjectiveId =7; 
delete from 'quest_objectives_locale_ru' where ObjectiveId =8; 
delete from 'quest_objectives_locale_ru' where ObjectiveId =9; 
delete from 'quest_objectives' where QuestId =5; 
insert into 'quest' (StartDialogId, EndDialogId, StartQuestEventType, EndQuestEventType) values ('0','0','0','0') ; 
insert into 'quest_locale_ru' (QuestId) values ('6'); 
update 'quest_locale_ru' SET Title = 'Помощь воинам', Description = 'Нужно помочь раздать лекарство всем потерпевшим.' where QuestId = '6'; 
update 'quest' SET StartDialogId = '32', EndDialogId = '30', StartQuestEventType = '1', EndQuestEventType = '1' where Id = '6'; 
insert into 'quest_objectives' (QuestId) values ('6') ; 
insert into 'quest_objectives_locale_ru' (ObjectiveId) values ('10'); 
update 'quest_locale_ru' SET Title = 'Помощь воинам', Description = 'Нужно помочь раздать лекарство всем потерпевшим.' where QuestId = '6'; 
update 'quest' SET StartDialogId = '32', EndDialogId = '30', StartQuestEventType = '1', EndQuestEventType = '1' where Id = '6'; 
update 'quest_objectives' SET Type='8', TargetId='35', Amount='1',isOptional ='0' where QuestId='6' and Id ='10'; 
update 'quest_objectives_locale_ru' SET Title='Дать лекарство NPC' where ObjectiveId = '10'; 
insert into 'quest_objectives' (QuestId) values ('6') ; 
insert into 'quest_objectives_locale_ru' (ObjectiveId) values ('11'); 
update 'quest_locale_ru' SET Title = 'Помощь воинам', Description = 'Нужно помочь раздать лекарство всем потерпевшим.' where QuestId = '6'; 
update 'quest' SET StartDialogId = '32', EndDialogId = '30', StartQuestEventType = '1', EndQuestEventType = '1' where Id = '6'; 
update 'quest_objectives' SET Type='8', TargetId='35', Amount='1',isOptional ='0' where QuestId='6' and Id ='10'; 
update 'quest_objectives_locale_ru' SET Title='Дать лекарство NPC' where ObjectiveId = '10'; 
update 'quest_objectives' SET Type='8', TargetId='37', Amount='1',isOptional ='0' where QuestId='6' and Id ='11'; 
update 'quest_objectives_locale_ru' SET Title='������' where ObjectiveId = '11'; 
insert into 'quest_objectives' (QuestId) values ('6') ; 
insert into 'quest_objectives_locale_ru' (ObjectiveId) values ('12'); 
update 'quest_locale_ru' SET Title = 'Помощь воинам', Description = 'Нужно помочь раздать лекарство всем потерпевшим.' where QuestId = '6'; 
update 'quest' SET StartDialogId = '32', EndDialogId = '30', StartQuestEventType = '1', EndQuestEventType = '1' where Id = '6'; 
update 'quest_objectives' SET Type='8', TargetId='35', Amount='1',isOptional ='0' where QuestId='6' and Id ='10'; 
update 'quest_objectives_locale_ru' SET Title='Дать лекарство NPC' where ObjectiveId = '10'; 
update 'quest_objectives' SET Type='8', TargetId='37', Amount='1',isOptional ='0' where QuestId='6' and Id ='11'; 
update 'quest_objectives_locale_ru' SET Title='������' where ObjectiveId = '11'; 
update 'quest_objectives' SET Type='8', TargetId='39', Amount='1',isOptional ='0' where QuestId='6' and Id ='12'; 
update 'quest_objectives_locale_ru' SET Title='������' where ObjectiveId = '12'; 
insert into 'quest_objectives' (QuestId) values ('6') ; 
insert into 'quest_objectives_locale_ru' (ObjectiveId) values ('13'); 
update 'quest_locale_ru' SET Title = 'Помощь воинам', Description = 'Нужно помочь раздать лекарство всем потерпевшим.' where QuestId = '6'; 
update 'quest' SET StartDialogId = '32', EndDialogId = '30', StartQuestEventType = '1', EndQuestEventType = '1' where Id = '6'; 
update 'quest_objectives' SET Type='8', TargetId='35', Amount='1',isOptional ='0' where QuestId='6' and Id ='10'; 
update 'quest_objectives_locale_ru' SET Title='Дать лекарство NPC' where ObjectiveId = '10'; 
update 'quest_objectives' SET Type='8', TargetId='37', Amount='1',isOptional ='0' where QuestId='6' and Id ='11'; 
update 'quest_objectives_locale_ru' SET Title='������' where ObjectiveId = '11'; 
update 'quest_objectives' SET Type='8', TargetId='39', Amount='1',isOptional ='0' where QuestId='6' and Id ='12'; 
update 'quest_objectives_locale_ru' SET Title='������' where ObjectiveId = '12'; 
update 'quest_objectives' SET Type='8', TargetId='42', Amount='1',isOptional ='0' where QuestId='6' and Id ='13'; 
update 'quest_objectives_locale_ru' SET Title='������' where ObjectiveId = '13'; 
update 'quest_locale_ru' SET Title = 'Помощь воинам', Description = 'Нужно помочь раздать лекарство всем потерпевшим.' where QuestId = '6'; 
update 'quest' SET StartDialogId = '32', EndDialogId = '30', StartQuestEventType = '1', EndQuestEventType = '1' where Id = '6'; 
update 'quest_objectives' SET Type='8', TargetId='35', Amount='1',isOptional ='0' where QuestId='6' and Id ='10'; 
update 'quest_objectives_locale_ru' SET Title='Дать лекарство NPC 1' where ObjectiveId = '10'; 
update 'quest_objectives' SET Type='8', TargetId='37', Amount='1',isOptional ='0' where QuestId='6' and Id ='11'; 
update 'quest_objectives_locale_ru' SET Title='Дать лекарство NPC 2' where ObjectiveId = '11'; 
update 'quest_objectives' SET Type='8', TargetId='39', Amount='1',isOptional ='0' where QuestId='6' and Id ='12'; 
update 'quest_objectives_locale_ru' SET Title='Дать лекарство NPC 3' where ObjectiveId = '12'; 
update 'quest_objectives' SET Type='8', TargetId='42', Amount='1',isOptional ='0' where QuestId='6' and Id ='13'; 
update 'quest_objectives_locale_ru' SET Title='Дать лекарство NPC 4' where ObjectiveId = '13'; 
