update 'dialogue_node' SET Npc_text ='Что ты хотел?' where Npc_id = 8 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Тебе помочь чем-нибудь?', To_node ='1', Quest_ID='5', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '29'; 
update 'dialogue_answers' SET Answer_text='Я сделал, что ты просила', To_node ='0', Quest_ID='5', End_dialogue='1', Start_quest='0', End_quest='1', Task_quest = '0'   where Id = '30'; 
update 'dialogue_answers' SET Answer_text='Ничего...', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '31'; 
update 'dialogue_node' SET Npc_text ='Да! Было бы неплохо. Помоги раздать всем воинам лекарство, Им нужно восстановить силы.' where Npc_id = 8 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='Хорошо', To_node ='0', Quest_ID='5', End_dialogue='0', Start_quest='1', End_quest='0', Task_quest = '0'   where Id = '32'; 
update 'dialogue_answers' SET Answer_text='Я помогу, но позже.', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '34'; 
update 'dialogue_node' SET Npc_text ='Что ты хотел?' where Npc_id = 8 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Тебе помочь чем-нибудь?', To_node ='1', Quest_ID='5', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '29'; 
update 'dialogue_answers' SET Answer_text='Я сделал, что ты просила', To_node ='0', Quest_ID='5', End_dialogue='1', Start_quest='0', End_quest='1', Task_quest = '0'   where Id = '30'; 
update 'dialogue_answers' SET Answer_text='Ничего...', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '31'; 
update 'dialogue_node' SET Npc_text ='Да! Было бы неплохо. Помоги раздать всем воинам лекарство, Им нужно восстановить силы.' where Npc_id = 8 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='Хорошо', To_node ='0', Quest_ID='5', End_dialogue='1', Start_quest='1', End_quest='0', Task_quest = '0'   where Id = '32'; 
update 'dialogue_answers' SET Answer_text='Я помогу, но позже.', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '34'; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('4','0','answer','0','0'); 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('4','3','npc text') ; 
update 'dialogue_node' SET Npc_text ='Ты чего пришел?' where Npc_id = 4 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='я по заданию 2', To_node ='1', Quest_ID='2', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '13'; 
update 'dialogue_answers' SET Answer_text='Просто так, забей', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '14'; 
update 'dialogue_answers' SET Answer_text='дай мне секретное задание 3', To_node ='2', Quest_ID='3', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '18'; 
update 'dialogue_answers' SET Answer_text='я выполнил секретное задание 3', To_node ='0', Quest_ID='3', End_dialogue='1', Start_quest='0', End_quest='1', Task_quest = '0'   where Id = '21'; 
update 'dialogue_answers' SET Answer_text='Держи лекарство.', To_node ='3', Quest_ID='5', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '41'; 
update 'dialogue_node' SET Npc_text ='О отлично! Иди в самое начало и там тебя наградят' where Npc_id = 4 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='ок', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '15'; 
update 'dialogue_node' SET Npc_text ='Откуда ты про него знаешь? Ну ладно, держи задание 3. Сходи и скажи " куку" 3 раза чуваку у колодца, а потом возвращайся ко мне.' where Npc_id = 4 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='хорошо я это сделаю', To_node ='0', Quest_ID='3', End_dialogue='1', Start_quest='1', End_quest='0', Task_quest = '0'   where Id = '19'; 
update 'dialogue_node' SET Npc_text ='Спасибо.' where Npc_id = 4 and Node_id = 3; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('4','3','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='Ты чего пришел?' where Npc_id = 4 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='я по заданию 2', To_node ='1', Quest_ID='2', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '13'; 
update 'dialogue_answers' SET Answer_text='Просто так, забей', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '14'; 
update 'dialogue_answers' SET Answer_text='дай мне секретное задание 3', To_node ='2', Quest_ID='3', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '18'; 
update 'dialogue_answers' SET Answer_text='я выполнил секретное задание 3', To_node ='0', Quest_ID='3', End_dialogue='1', Start_quest='0', End_quest='1', Task_quest = '0'   where Id = '21'; 
update 'dialogue_answers' SET Answer_text='Держи лекарство.', To_node ='3', Quest_ID='5', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '41'; 
update 'dialogue_node' SET Npc_text ='О отлично! Иди в самое начало и там тебя наградят' where Npc_id = 4 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='ок', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '15'; 
update 'dialogue_node' SET Npc_text ='Откуда ты про него знаешь? Ну ладно, держи задание 3. Сходи и скажи " куку" 3 раза чуваку у колодца, а потом возвращайся ко мне.' where Npc_id = 4 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='хорошо я это сделаю', To_node ='0', Quest_ID='3', End_dialogue='1', Start_quest='1', End_quest='0', Task_quest = '0'   where Id = '19'; 
update 'dialogue_node' SET Npc_text ='Спасибо.' where Npc_id = 4 and Node_id = 3; 
update 'dialogue_answers' SET Answer_text='На здоровье', To_node ='0', Quest_ID='5', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '42'; 
