insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('1','0','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='Привет хочешь квест?' where Npc_id = 1 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='да', To_node ='1', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '1'; 
update 'dialogue_answers' SET Answer_text='нет', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '2'; 
update 'dialogue_answers' SET Answer_text='Я вобщето насчет задания 2.', To_node ='2', Quest_ID='2', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '16'; 
update 'dialogue_answers' SET Answer_text='Держи, это восстановит твои силы.', To_node ='0', Quest_ID='5', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '35'; 
update 'dialogue_node' SET Npc_text ='квест 1, сходи к челу у колодца' where Npc_id = 1 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='хорошо', To_node ='0', Quest_ID='1', End_dialogue='1', Start_quest='1', End_quest='0', Task_quest = '0'   where Id = '3'; 
update 'dialogue_node' SET Npc_text ='Ааа, вот оно что, держи награду' where Npc_id = 1 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='спасибо', To_node ='0', Quest_ID='2', End_dialogue='1', Start_quest='0', End_quest='1', Task_quest = '0'   where Id = '17'; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('1','3','npc text') ; 
update 'dialogue_node' SET Npc_text ='Привет хочешь квест?' where Npc_id = 1 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='да', To_node ='1', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '1'; 
update 'dialogue_answers' SET Answer_text='нет', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '2'; 
update 'dialogue_answers' SET Answer_text='Я вобщето насчет задания 2.', To_node ='2', Quest_ID='2', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '16'; 
update 'dialogue_answers' SET Answer_text='Держи, это восстановит твои силы.', To_node ='3', Quest_ID='5', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '35'; 
update 'dialogue_node' SET Npc_text ='квест 1, сходи к челу у колодца' where Npc_id = 1 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='хорошо', To_node ='0', Quest_ID='1', End_dialogue='1', Start_quest='1', End_quest='0', Task_quest = '0'   where Id = '3'; 
update 'dialogue_node' SET Npc_text ='Ааа, вот оно что, держи награду' where Npc_id = 1 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='спасибо', To_node ='0', Quest_ID='2', End_dialogue='1', Start_quest='0', End_quest='1', Task_quest = '0'   where Id = '17'; 
update 'dialogue_node' SET Npc_text ='npc text' where Npc_id = 1 and Node_id = 3; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('1','3','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='Привет хочешь квест?' where Npc_id = 1 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='да', To_node ='1', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '1'; 
update 'dialogue_answers' SET Answer_text='нет', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '2'; 
update 'dialogue_answers' SET Answer_text='Я вобщето насчет задания 2.', To_node ='2', Quest_ID='2', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '16'; 
update 'dialogue_answers' SET Answer_text='Держи, это восстановит твои силы.', To_node ='3', Quest_ID='5', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '35'; 
update 'dialogue_node' SET Npc_text ='квест 1, сходи к челу у колодца' where Npc_id = 1 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='хорошо', To_node ='0', Quest_ID='1', End_dialogue='1', Start_quest='1', End_quest='0', Task_quest = '0'   where Id = '3'; 
update 'dialogue_node' SET Npc_text ='Ааа, вот оно что, держи награду' where Npc_id = 1 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='спасибо', To_node ='0', Quest_ID='2', End_dialogue='1', Start_quest='0', End_quest='1', Task_quest = '0'   where Id = '17'; 
update 'dialogue_node' SET Npc_text ='Спасибо тебе' where Npc_id = 1 and Node_id = 3; 
update 'dialogue_answers' SET Answer_text='Удачи.', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '36'; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('2','0','answer','0','0'); 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('2','2','npc text') ; 
update 'dialogue_node' SET Npc_text ='о привет ты зачем пришел?' where Npc_id = 2 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='меня просили по квест 1 зайти к тебе', To_node ='1', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '4'; 
update 'dialogue_answers' SET Answer_text='просто так, пока', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '5'; 
update 'dialogue_answers' SET Answer_text='ку-ку', To_node ='0', Quest_ID='3', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '20'; 
update 'dialogue_answers' SET Answer_text='На, возьми лекарство, оно поможет.', To_node ='2', Quest_ID='5', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '37'; 
update 'dialogue_node' SET Npc_text ='о понятно, тогда сходи к челу у дома напротив, он тебя наградит' where Npc_id = 2 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='ок спасибо', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '7'; 
update 'dialogue_answers' SET Answer_text='ясно понятно', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '8'; 
update 'dialogue_node' SET Npc_text ='О-о-о, благодарю тебя.' where Npc_id = 2 and Node_id = 2; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('2','2','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='о привет ты зачем пришел?' where Npc_id = 2 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='меня просили по квест 1 зайти к тебе', To_node ='1', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '4'; 
update 'dialogue_answers' SET Answer_text='просто так, пока', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '5'; 
update 'dialogue_answers' SET Answer_text='ку-ку', To_node ='0', Quest_ID='3', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '20'; 
update 'dialogue_answers' SET Answer_text='На, возьми лекарство, оно поможет.', To_node ='2', Quest_ID='5', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '37'; 
update 'dialogue_node' SET Npc_text ='о понятно, тогда сходи к челу у дома напротив, он тебя наградит' where Npc_id = 2 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='ок спасибо', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '7'; 
update 'dialogue_answers' SET Answer_text='ясно понятно', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '8'; 
update 'dialogue_node' SET Npc_text ='О-о-о, благодарю тебя.' where Npc_id = 2 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='Держись', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '38'; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('3','0','answer','0','0'); 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('3','3','npc text') ; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('3','3','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='О привет, ты по квесту?' where Npc_id = 3 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='да', To_node ='1', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='1', Task_quest = '0'   where Id = '9'; 
update 'dialogue_answers' SET Answer_text='Я принес тебе лекарство.', To_node ='3', Quest_ID='5', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '39'; 
update 'dialogue_node' SET Npc_text ='Молодец вот тебе награда.
Хочешь еще задание?' where Npc_id = 3 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='спасибо нет', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '10'; 
update 'dialogue_answers' SET Answer_text='Да, давай еще одно задание!', To_node ='2', Quest_ID='2', End_dialogue='0', Start_quest='1', End_quest='0', Task_quest = '0'   where Id = '11'; 
update 'dialogue_node' SET Npc_text ='Сходи к самому дальнему дому и поговори с нпс' where Npc_id = 3 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='хорошо', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '12'; 
update 'dialogue_node' SET Npc_text ='кхк...кхк..Спасибо' where Npc_id = 3 and Node_id = 3; 
update 'dialogue_answers' SET Answer_text='Надеюсь тебе станет легче.', To_node ='0', Quest_ID='0', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '40'; 
