insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('1','0','npc text') ; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('1','0','answer','0','0'); 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('1','1','npc text') ; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('1','1','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='Привет. Я Эрик, чем могу быть полезен?' where Npc_id = 1 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Привет! Это твоя кузина пропала? ', To_node ='1', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '1'; 
update 'dialogue_node' SET Npc_text ='Да, моя печальная Долли. Моя дочь заболела и Долли предложила помочь. Я весь день на конюшне работаю, не отвлечься ни на минуту, а дочери нужно лекарство. Вот Долли и предложила сходить на болото за ягодами, говорит, что её знакомая знахарка знает рецепт зелья от этой хвори. Вот уже три дня назад ушла на топи, да так и не вернулась. Всё обыскал там, ничего не нашел. Помоги, чем сможешь. Может, знахарка знает что-то про те места. ' where Npc_id = 1 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='Я сделаю все, что в моих Силах.', To_node ='0', Quest_ID='1', End_dialogue='1', Start_quest='1', End_quest='0', Task_quest = '0'   where Id = '2'; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('2','0','npc text') ; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('2','1','npc text') ; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('2','0','answer','0','0'); 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('2','1','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='Добро пожаловать в Травяную Лавку, желаете приобрести что-нибудь?' where Npc_id = 2 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Привет, я от Эрика. Он говорит, твоя подруга Долли пропала в топях. Ты что-нибудь знаешь? ', To_node ='1', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '3'; 
update 'dialogue_node' SET Npc_text ='Да, приходила ко мне на днях, спрашивала про лекарство от горячки, я ей и сказала найти ягоды желтоцвета. Только я не советовала ей ходить на Воющие топи, там слишком опасно для одинокой девушки. ' where Npc_id = 2 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='Что там такого опасного? ', To_node ='0', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '4'; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('2','2','npc text') ; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('2','2','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='Добро пожаловать в Травяную Лавку, желаете приобрести что-нибудь?' where Npc_id = 2 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Привет, я от Эрика. Он говорит, твоя подруга Долли пропала в топях. Ты что-нибудь знаешь? ', To_node ='1', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '3'; 
update 'dialogue_node' SET Npc_text ='Да, приходила ко мне на днях, спрашивала про лекарство от горячки, я ей и сказала найти ягоды желтоцвета. Только я не советовала ей ходить на Воющие топи, там слишком опасно для одинокой девушки. ' where Npc_id = 2 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='Что там такого опасного? ', To_node ='2', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '4'; 
update 'dialogue_node' SET Npc_text ='Раньше там росло одно растение дурманящее. Только чувствуешь его запах, как мысли страшные в голову лезут, как будто топь сама манит тебя и пытается затянуть в свои трясины. И примерно год назад пропал один охотник, который выслеживал дичь в тех краях. Больше охотника никто не видел, но, что странно, цветков этого растения больше нет, как будто кто-то их собирает постоянно… Гиблое дело, скажу я тебе. ' where Npc_id = 2 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='Так Долли пошла туда одна? ', To_node ='0', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '5'; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('2','3','npc text') ; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('2','3','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='Добро пожаловать в Травяную Лавку, желаете приобрести что-нибудь?' where Npc_id = 2 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Привет, я от Эрика. Он говорит, твоя подруга Долли пропала в топях. Ты что-нибудь знаешь? ', To_node ='1', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '3'; 
update 'dialogue_node' SET Npc_text ='Да, приходила ко мне на днях, спрашивала про лекарство от горячки, я ей и сказала найти ягоды желтоцвета. Только я не советовала ей ходить на Воющие топи, там слишком опасно для одинокой девушки. ' where Npc_id = 2 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='Что там такого опасного? ', To_node ='2', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '4'; 
update 'dialogue_node' SET Npc_text ='Раньше там росло одно растение дурманящее. Только чувствуешь его запах, как мысли страшные в голову лезут, как будто топь сама манит тебя и пытается затянуть в свои трясины. И примерно год назад пропал один охотник, который выслеживал дичь в тех краях. Больше охотника никто не видел, но, что странно, цветков этого растения больше нет, как будто кто-то их собирает постоянно… Гиблое дело, скажу я тебе. ' where Npc_id = 2 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='Так Долли пошла туда одна? ', To_node ='3', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '5'; 
update 'dialogue_node' SET Npc_text ='Не знаю, я советовала ей пойти в Лес высокой травы, там желтоцвет тоже растет, хоть и не так часто. Может, она всё же послушала совета, кто знает. ' where Npc_id = 2 and Node_id = 3; 
update 'dialogue_answers' SET Answer_text='Спасибо, проверю там. ', To_node ='0', Quest_ID='1', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '6'; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('3','0','npc text') ; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('3','1','npc text') ; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('3','2','npc text') ; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('3','0','answer','0','0'); 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('3','1','answer','0','0'); 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('3','2','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='Ты кто такой? Что тебе надо от старой женщины? ' where Npc_id = 3 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Я ищу Долли и нашел у неё твои рецепты зелий. Может, ты что-нибудь знаешь про неё? ', To_node ='1', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '7'; 
update 'dialogue_node' SET Npc_text ='Тебе-то зачем? Ты не местный тут, какое тебе дело? ' where Npc_id = 3 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='Она пропала, три дня уже никто про неё ничего не слышал. ', To_node ='2', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '8'; 
update 'dialogue_node' SET Npc_text ='Всё же пошла к нему…' where Npc_id = 3 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='К кому? Кому она ушла? ', To_node ='0', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '9'; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('3','3','npc text') ; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('3','4','npc text') ; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('3','3','answer','0','0'); 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('3','4','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='Ты кто такой? Что тебе надо от старой женщины? ' where Npc_id = 3 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Я ищу Долли и нашел у неё твои рецепты зелий. Может, ты что-нибудь знаешь про неё? ', To_node ='1', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '7'; 
update 'dialogue_node' SET Npc_text ='Тебе-то зачем? Ты не местный тут, какое тебе дело? ' where Npc_id = 3 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='Она пропала, три дня уже никто про неё ничего не слышал. ', To_node ='2', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '8'; 
update 'dialogue_node' SET Npc_text ='Всё же пошла к нему…' where Npc_id = 3 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='К кому? Кому она ушла? ', To_node ='3', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '9'; 
update 'dialogue_node' SET Npc_text ='К возлюбленному своему, Дориану… Год назад Дориан ушел на болота охотиться, вот только не знал он, что нельзя подходить близко к огнелисту. Его запах дурманит и человек сам топится в болоте, только утонуть никак не может. Чудовищем становится, которое только и пытается, что собрать все огнелисты и утопиться с ними. И нападает на всех, кто приблизится к его топям. Долли только не трогал первое время. Она пыталась его вылечить, собирала разные травы, я придумывала для неё новые рецепты, только всё без толку оказалось. Не спасти уже его, слишком много времени прошло. Отчаялась она уже и думала пойти к нему, разделить его судьбу. Я отговаривала её как могла, но раз её нигде нет, то она явно решилась бросить всё ради своей любви.' where Npc_id = 3 and Node_id = 3; 
update 'dialogue_answers' SET Answer_text='Что ты знаешь про это чудовище? ', To_node ='4', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '10'; 
update 'dialogue_node' SET Npc_text ='Мы с Долли много что перепробовали, единственное, что давало хоть какой-то результат, это зелья, в которых были примеси серебра. Они как будто жгли его изнутри, мы думали, так изгнать из него эту заразу, только он отказывался их пить потом, отбрасывал Долли, а сам убегал куда-то вглубь топей и несколько дней его не было видно. ' where Npc_id = 3 and Node_id = 4; 
update 'dialogue_answers' SET Answer_text='Надо поспешить, может, я успею её еще спасти. ', To_node ='0', Quest_ID='1', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '11'; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('4','0','npc text') ; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('4','1','npc text') ; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('4','2','npc text') ; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('4','0','answer','0','0'); 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('4','1','answer','0','0'); 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('4','2','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='*Долли бродит по полянке и ищет огнелист*
Что тебе надо?' where Npc_id = 4 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Долли! Что ты тут делаешь? Что бы ты ни задумала, брось это, это не стоит того! ', To_node ='1', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '12'; 
update 'dialogue_node' SET Npc_text ='Ты не понимаешь, я люблю его! Я стану как он и мы вечно будем вместе!' where Npc_id = 4 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='answer', To_node ='2', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '13'; 
update 'dialogue_node' SET Npc_text ='Его дочь и так поправится, эта горячка и сама пройдет, а кто вылечит Дориана? Кто позаботится о нем? Я должна это сделать, надо всего лишь собрать побольше огнелистов и мы станем навсегда вместе… ' where Npc_id = 4 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='Это уже не Дориан, он уже не человек и не способен на чувства, он опасен для тебя и для жителей. Вернись домой, пока не поздно, мы что-нибудь придумаем… ', To_node ='0', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '14'; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('4','3','npc text') ; 
update 'dialogue_node' SET Npc_text ='*Долли бродит по полянке и ищет огнелист*
Что тебе надо?' where Npc_id = 4 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Долли! Что ты тут делаешь? Что бы ты ни задумала, брось это, это не стоит того! ', To_node ='1', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '12'; 
update 'dialogue_node' SET Npc_text ='Ты не понимаешь, я люблю его! Я стану как он и мы вечно будем вместе!' where Npc_id = 4 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='answer', To_node ='2', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '13'; 
update 'dialogue_node' SET Npc_text ='Его дочь и так поправится, эта горячка и сама пройдет, а кто вылечит Дориана? Кто позаботится о нем? Я должна это сделать, надо всего лишь собрать побольше огнелистов и мы станем навсегда вместе… ' where Npc_id = 4 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='Это уже не Дориан, он уже не человек и не способен на чувства, он опасен для тебя и для жителей. Вернись домой, пока не поздно, мы что-нибудь придумаем… ', To_node ='0', Quest_ID='0', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '14'; 
update 'dialogue_node' SET Npc_text ='*Долли отворачивается и уходит к топям.*' where Npc_id = 4 and Node_id = 3; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('4','3','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='*Долли бродит по полянке и ищет огнелист*
Что тебе надо?' where Npc_id = 4 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Долли! Что ты тут делаешь? Что бы ты ни задумала, брось это, это не стоит того! ', To_node ='1', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '12'; 
update 'dialogue_node' SET Npc_text ='Ты не понимаешь, я люблю его! Я стану как он и мы вечно будем вместе!' where Npc_id = 4 and Node_id = 1; 
update 'dialogue_answers' SET Answer_text='Чудовищем? Ты хочешь стать монстром, который вечно пытается утопиться? Подумай об Эрике, о его дочке! Ты же хотела помочь им, они ждут тебя, беспокоятся о тебе!', To_node ='2', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '13'; 
update 'dialogue_node' SET Npc_text ='Его дочь и так поправится, эта горячка и сама пройдет, а кто вылечит Дориана? Кто позаботится о нем? Я должна это сделать, надо всего лишь собрать побольше огнелистов и мы станем навсегда вместе… ' where Npc_id = 4 and Node_id = 2; 
update 'dialogue_answers' SET Answer_text='Это уже не Дориан, он уже не человек и не способен на чувства, он опасен для тебя и для жителей. Вернись домой, пока не поздно, мы что-нибудь придумаем… ', To_node ='3', Quest_ID='1', End_dialogue='0', Start_quest='0', End_quest='0', Task_quest = '0'   where Id = '14'; 
update 'dialogue_node' SET Npc_text ='*Долли отворачивается и уходит к топям.*' where Npc_id = 4 and Node_id = 3; 
update 'dialogue_answers' SET Answer_text='Нужно проследить за ней!', To_node ='0', Quest_ID='1', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '15'; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('5','0','npc text') ; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('5','0','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='Кажется, Долли всё же пошла в этот лес по совету знахарки. Следы человека, сорванные желтоцветы, вот только самой Долли нигде не видно, да и в городе она не появлялась. 

В траве блестит что-то небольшое и медное. Кажется, это ключ от дома. Может, стоит наведаться к дому Долли. ' where Npc_id = 5 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Взять ключ', To_node ='0', Quest_ID='1', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '16'; 
insert into 'dialogue_node' (Npc_id, Node_ID, Npc_text) values ('6','0','npc text') ; 
insert into 'dialogue_answers' (Npc_id, Node_ID, Answer_text, To_node, End_dialogue) values ('6','0','answer','0','0'); 
update 'dialogue_node' SET Npc_text ='В комнате по всем столам разложены странные цветы, какие-то из них засохли, какие-то почти что свежие. В помещении стоит дурманящий запах, навевающий темные мысли. 

По полу разбросаны многочисленные рецепты зелий, написанные, что странно, не Изольдой, а какой-то Гретой. Надо найти её и поговорить. Может, она знает что-то про Долли. ' where Npc_id = 6 and Node_id = 0; 
update 'dialogue_answers' SET Answer_text='Уйти на поиски Греты', To_node ='0', Quest_ID='1', End_dialogue='1', Start_quest='0', End_quest='0', Task_quest = '1'   where Id = '17'; 
